// src/pages/Home.vue
<script setup>
import DefaultLayout from '@/layouts/DefaultLayout.vue'
import CategoriesSection from '@/components/CategoriesSection.vue'
import CollectionsSection from '@/components/CollectionsSection.vue'
import FeaturedEventsSection from '@/components/FeaturedEventsSection.vue'
import HeroSection from '@/components/HeroSection.vue'
import InfoSection from '@/components/InfoSection.vue'

import PButton from 'primevue/button'
</script>

<template>
  <DefaultLayout root-class="min-h-screen flex flex-col bg-white">
    <HeroSection />
    <CollectionsSection />
    <FeaturedEventsSection />
    <CategoriesSection />
    <InfoSection />
  </DefaultLayout>
</template>

// ticket-sales-site/client/src/pages/Home.tsx
import Header from '@/components/Header';
import HeroSection from '@/components/HeroSection';
import CategoriesSection from '@/components/CategoriesSection';
import FeaturedEventsSection from '@/components/FeaturedEventsSection';
import InfoSection from '@/components/InfoSection';
import Footer from '@/components/Footer';

export default function Home() {
  return (
    <div className="min-h-screen flex flex-col bg-white">
      <Header />
      <main className="flex-1">
        <HeroSection />
        <CategoriesSection />
        <FeaturedEventsSection />
        <InfoSection />
      </main>
      <Footer />
    </div>
  );
}
