// ticket-sales-site/client/src/components/Header.tsx
import { useState } from 'react';
import { Search, MapPin, Menu, X } from 'lucide-react';
import { Button } from '@/components/ui/button';

export default function Header() {
  const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');

  return (
    <header className="sticky top-0 z-50 bg-gradient-to-r from-[#0F3460] to-[#2E8BC0] shadow-lg">
      <div className="container mx-auto px-4 py-4">
        <div className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-2 flex-shrink-0">
            <div className="w-10 h-10 bg-[#D4AF37] rounded-lg flex items-center justify-center">
              <span className="text-[#0F3460] font-bold text-lg">M</span>
            </div>
            <div className="hidden sm:block">
              <h1 className="text-white font-bold text-lg">Mirante</h1>
              <p className="text-[#D4AF37] text-xs font-semibold">Ingressos</p>
            </div>
          </div>

          <div className="hidden md:flex flex-1 max-w-md mx-4">
            <div className="w-full relative">
              <input
                type="text"
                placeholder="Buscar experiencias"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full px-4 py-3 rounded-lg bg-white text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-[#D4AF37]"
              />
              <Search className="absolute right-3 top-3.5 text-gray-400 w-5 h-5" />
            </div>
          </div>

          <div className="hidden sm:flex items-center gap-2 bg-white/10 px-3 py-2 rounded-lg text-white hover:bg-white/20 transition-colors cursor-pointer">
            <MapPin className="w-4 h-4" />
            <span className="text-sm font-medium">Boa Vista</span>
          </div>

          <nav className="hidden lg:flex items-center gap-6 text-white">
            <a href="#" className="text-sm font-medium hover:text-[#D4AF37] transition-colors">Meus Ingressos</a>
            <a href="#" className="text-sm font-medium hover:text-[#D4AF37] transition-colors">Criar Evento</a>
            <Button className="bg-[#D4AF37] text-[#0F3460] hover:bg-white font-semibold">Entrar</Button>
          </nav>

          <button
            onClick={() => setMobileMenuOpen(!mobileMenuOpen)}
            className="lg:hidden text-white p-2 hover:bg-white/10 rounded-lg transition-colors"
          >
            {mobileMenuOpen ? <X className="w-6 h-6" /> : <Menu className="w-6 h-6" />}
          </button>
        </div>

        <div className="md:hidden mt-4">
          <div className="w-full relative">
            <input
              type="text"
              placeholder="Buscar experiencias"
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="w-full px-4 py-3 rounded-lg bg-white text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-[#D4AF37]"
            />
            <Search className="absolute right-3 top-3.5 text-gray-400 w-5 h-5" />
          </div>
        </div>
      </div>

      {mobileMenuOpen && (
        <div className="lg:hidden bg-[#0D2A47] border-t border-white/10">
          <div className="container mx-auto px-4 py-4 space-y-3">
            <a href="#" className="block text-white text-sm font-medium py-2 hover:text-[#D4AF37] transition-colors">
              Meus Ingressos
            </a>
            <a href="#" className="block text-white text-sm font-medium py-2 hover:text-[#D4AF37] transition-colors">
              Criar Evento
            </a>
            <Button className="w-full bg-[#D4AF37] text-[#0F3460] hover:bg-white font-semibold">Entrar</Button>
          </div>
        </div>
      )}
    </header>
  );
}

// src/components/Header.vue
<script setup>
import { ref } from 'vue'
import { MapPin, Menu, Search, X } from 'lucide-vue-next'

import Button from '@/components/ui/Button.vue'
import logoMirante from '@/assets/images/logo-colorido.png'

const mobileMenuOpen = ref(false)
const searchQuery = ref('')
</script>

<template>
  <header class="sticky top-0 z-50 bg-gradient-to-r from-[#0F3460] to-[#2E8BC0] shadow-lg">
    <div class="container mx-auto px-4 py-4">
      <div class="flex items-center justify-between gap-4">
        <RouterLink
          to="/"
          class="flex items-center gap-3 flex-shrink-0 hover:opacity-90 transition-opacity"
        >
          <div class="bg-white rounded-xl p-2.5 shadow-lg hover:shadow-xl transition-all duration-300 border border-white/20">
            <img :src="logoMirante" alt="Mirante Edileusa Lóz" class="h-10 md:h-12 w-auto object-contain" />
          </div>
         
        </RouterLink>

        <div class="hidden md:flex flex-1 max-w-md mx-4">
          <div class="w-full relative">
            <input
              v-model="searchQuery"
              type="text"
              placeholder="Buscar experiencias"
              class="w-full px-4 py-3 rounded-lg bg-white text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-[#D4AF37]"
            />
            <Search class="absolute right-3 top-3.5 text-gray-400 w-5 h-5" />
          </div>
        </div>

        <div
          class="hidden sm:flex items-center gap-2 bg-white/10 px-3 py-2 rounded-lg text-white hover:bg-white/20 transition-colors cursor-pointer"
        >
          <MapPin class="w-4 h-4" />
          <span class="text-sm font-medium">Boa Vista</span>
        </div>

        <nav class="hidden lg:flex items-center gap-6 text-white">
          <RouterLink to="/o-mirante" class="text-sm font-medium hover:text-[#D4AF37] transition-colors">
            O Mirante
          </RouterLink>
          <RouterLink to="/meus-ingressos" class="text-sm font-medium hover:text-[#D4AF37] transition-colors">
            Meus Ingressos
          </RouterLink>
          <a href="https://boavista.rr.gov.br/visita360/index.htm" target="_blank" rel="noopener noreferrer" class="text-sm font-medium hover:text-[#D4AF37] transition-colors">Visão 360º</a>
          <a href="#" class="text-sm font-medium hover:text-[#D4AF37] transition-colors">Criar Evento</a>
          <Button class="bg-[#D4AF37] text-[#0F3460] hover:bg-white font-semibold">Entrar</Button>
        </nav>

        <button
          class="lg:hidden text-white p-2 hover:bg-white/10 rounded-lg transition-colors"
          @click="mobileMenuOpen = !mobileMenuOpen"
        >
          <X v-if="mobileMenuOpen" class="w-6 h-6" />
          <Menu v-else class="w-6 h-6" />
        </button>
      </div>

      <div class="md:hidden mt-4">
        <div class="w-full relative">
          <input
            v-model="searchQuery"
            type="text"
            placeholder="Buscar experiencias"
            class="w-full px-4 py-3 rounded-lg bg-white text-gray-900 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-[#D4AF37]"
          />
          <Search class="absolute right-3 top-3.5 text-gray-400 w-5 h-5" />
        </div>
      </div>
    </div>

    <div v-if="mobileMenuOpen" class="lg:hidden bg-[#0D2A47] border-t border-white/10">
      <div class="container mx-auto px-4 py-4 space-y-3">
        <RouterLink
          to="/o-mirante"
          class="block text-white text-sm font-medium py-2 hover:text-[#D4AF37] transition-colors"
          @click="mobileMenuOpen = false"
        >
          O Mirante
        </RouterLink>
        <RouterLink
          to="/meus-ingressos"
          class="block text-white text-sm font-medium py-2 hover:text-[#D4AF37] transition-colors"
          @click="mobileMenuOpen = false"
        >
          Meus Ingressos
        </RouterLink>
        <a href="https://boavista.rr.gov.br/visita360/index.htm" target="_blank" rel="noopener noreferrer" class="block text-white text-sm font-medium py-2 hover:text-[#D4AF37] transition-colors" @click="mobileMenuOpen = false">
          Visão 360º
        </a>
        <a href="#" class="block text-white text-sm font-medium py-2 hover:text-[#D4AF37] transition-colors">
          Criar Evento
        </a>
        <Button class="w-full bg-[#D4AF37] text-[#0F3460] hover:bg-white font-semibold">Entrar</Button>
      </div>
    </div>
  </header>
</template>
